# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files

-   repo: https://github.com/hadialqattan/pycln  # Remove unused imports
    rev: v1.3.3
    hooks:
    -   id: pycln

-   repo: https://github.com/PyCQA/isort  # sort import the py way
    rev: 5.11.5
    hooks:
    -   id: isort
        args: ["--profile", "black", --line-length=120]

-   repo: https://github.com/psf/black  # python code style formatter "any color so long as it is black"
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--line-length=120]

-   repo: https://github.com/pycqa/flake8  # python coding style guide PEP8
    rev: 4.0.1
    hooks:
    -   id: flake8

-   repo: https://github.com/pycqa/pylint  # python linter code analysis
    rev: v2.14.1
    hooks:
    -   id: pylint
        args: [--rcfile=.pylintrc]

# TODO: For now we're ignoring mypy, let's use it in the future
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.931
#    hooks:
#        - id: mypy
#          args: [--config-file=pyproject.toml, --no-warn-no-return, --show-error-codes]
#          additional_dependencies: [pydantic]  # add if use pydantic
