FROM continuumio/anaconda3:2022.10

SHELL ["/bin/bash", "-c"]

COPY setup/environment.yml /VariantCalling/setup/
COPY setup/other_envs/cutadaptenv.yml /VariantCalling/setup/other_envs/
COPY setup/other_envs/ucsc.yml /VariantCalling/setup/other_envs/
COPY setup/other_envs/cnmops.yml /VariantCalling/setup/other_envs/

RUN conda env create -f /VariantCalling/setup/environment.yml && \
    conda env create -f /VariantCalling/setup/other_envs/cutadaptenv.yml && \
    conda env create -f /VariantCalling/setup/other_envs/ucsc.yml && \
    conda env create -f /VariantCalling/setup/other_envs/cnmops.yml && \
    conda init --all

## install ug-cn.mops (branch: tammy/enable_moderate_amplifications_test):
RUN cd /opt && \
   git clone --branch tammy/enable_moderate_amplifications_test https://github.com/Ultimagen/cn.mops.git cn.mops && \
   cd cn.mops && \
   git checkout 5f870ea11d23f15f4890cd0c6d66821d56b381bf

RUN source ~/.bashrc && \
   conda activate cn.mops && \
   Rscript -e 'remove.packages("cn.mops")' && \
   R CMD INSTALL --preclean --no-multiarch --with-keep.source /opt/cn.mops/ && \
   conda deactivate

RUN source ~/.bashrc && \
    conda activate genomics.py3 && \
    pip install mpld3==0.5.1

COPY . /VariantCalling

RUN source ~/.bashrc && \
    conda activate genomics.py3 && \
    cd /VariantCalling && \
    pip install .

# Include licenses
COPY ["Ultima UGVC - EULA.pdf", "./"]
COPY ["Third Party Licenses/", "./Third Party Licenses/"]
