name: scrna_qc
run-name: "Build scRNA qc Docker Image"

on:
  push:
    branches:
      - main
      - master
      - release_*
    paths:
      - setup/scRNA_qc/pyproject.toml
      - ugvc/pipelines/single_cell_qc/*.py
      - ugvc/reports/single_cell_qc_report.ipynb
  workflow_dispatch:

permissions:
  id-token: write # Required for assuming an AWS role
  contents: read # Required for actions/checkout

env:
  AWS_REGION: us-east-1
  AWS_ROLE: arn:aws:iam::337532070941:role/google-aws-sync-aws-role

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: false

      - uses: actions/checkout@v3
        with:
          submodules: true

      # setup python and update the version in pyproject.toml
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry
        run: |
            curl -sSL https://install.python-poetry.org | python3 -

      - name: Update Version
        run: |
            scrna_qc_version=$($HOME/.local/bin/poetry version --short)
            echo "DOCKER_TAG=${scrna_qc_version}" >> ${GITHUB_ENV}
        working-directory: setup/scRNA_qc

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract build parameters
        run: |
          echo "BUILD_TIMESTAMP=$(date '+%F_%H:%M:%S')" >> ${GITHUB_ENV}
          echo "BUILD_VERSION=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}

      - name: Build and push scrna_qc docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: setup/scRNA_qc/Dockerfile
          push: true
          tags: ${{ steps.ecr-login.outputs.registry }}/scrna_qc:${{ env.DOCKER_TAG }}
          build-args: |
            VERSION=${{ env.DOCKER_TAG }}
            BUILD_TIMESTAMP=${{ env.BUILD_TIMESTAMP }}
            BUILD_VERSION=${{ env.BUILD_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
