name: Build VC Docker image

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: "Docker image tag"
        required: true
        type: string

permissions:
  id-token: write # Required for assuming an AWS role
  contents: read # Required for actions/checkout

env:
  AWS_REGION: us-east-1
  AWS_ROLE_NAME: github-actions-ecr
  AWS_ACCOUNT: 337532070941

  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/55428976747/locations/global/workloadIdentityPools/devops-pool/providers/devops-pool-provider
  GCP_SERVICE_ACCOUNT: gcr-push-sa@ultima-data-307918.iam.gserviceaccount.com

  IMAGE: ugvc

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
