name: Python Package using Conda

on: [ push ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: True
      - name: Setup file system
        run: |
          sudo mkdir -p /data
          sudo chmod 777 /data
      - name: Setup environment variables
        run: |
          export PAPYRUS_ACCESS_STRING=mongodb+srv://inigo-montoya:1aBc5678910@testcluster.jm2x3.mongodb.net/test
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file setup/other_envs/ucsc.yml --name ucsc
          conda env create -f setup/other_envs/cutadapt.yml --name cutadapt
          conda env update --file setup/environment.yml --name base
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest --ignore src/python_tests/test_db_access.py
